### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by Chiny91** [VREMSoftwareDevelopment/rstats-cstats#1]
Although I have run _easyTomato_ for many years, I have never really taken much notice of any stats.   Having a bit more time these days, I have finally got round to looking, so this software was an interesting find.   I've no stats to view other than those of today but still...

It would be useful to have options to display the bytes count in MB and GB.

**Comment by VREMSoftwareDevelopment** [comment]
That does sound like a very useful feature to have! At the moment I am working on features for a few other personal projects. Would you be interested in adding this feature via a pull request?

Just for reference: https://guides.github.com/activities/contributing-to-open-source/
