### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by xi0n-io** [VREMSoftwareDevelopment/rstats-cstats#3]
I got this error, used the latest version of the script and the latest python 3 release version

```
>>>>>>>>>> Tomato USB CSTATS <<<<<<<<<<
File size: 77760
Number of records: 5.680888369374634
Traceback (most recent call last):
  File "cstats.py", line 164, in <module>
    main()
  File "cstats.py", line 158, in main
    CStats(args[0]).dump()
  File "cstats.py", line 57, in dump
    for i in range(self.records):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by dmorrison42** [comment]
Quick drive by commit here just to get it up and running with recent versions of python.

Happy to clean it up, but this should be enough if someone is just looking to be able to read one of the backup files.

https://github.com/VREMSoftwareDevelopment/rstats-cstats/pull/4
